import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react'

export type ThemeMode = 'light' | 'dark' | 'system'
export type Language = 'en' | 'ru'

type TranslationDict = Record<string, string>

const STORAGE_THEME = 'lfb:theme'
const STORAGE_LANGUAGE = 'lfb:language'

const translations: Record<Language, TranslationDict> = {
  en: {
    'app.title': 'Lost & Found Board',
    'nav.items': 'Items',
    'nav.report': 'Create Report',
    'nav.myReports': 'My Reports',
    'nav.profile': 'Profile',
    'nav.moderation': 'Moderation',
    'role.admin': 'Admin Console',
    'role.moderator': 'Moderator Console',
    'settings.title': 'Settings',
    'settings.subtitle': 'Personalize appearance and language',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.system': 'System',
    'settings.language': 'Language',
    'settings.language.en': 'English',
    'settings.language.ru': 'Русский',
    'common.loading': 'Loading…',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.reset': 'Reset',
    'common.clearAll': 'Clear all',
    'common.filters': 'Filters',
    'common.hideFilters': 'Hide filters',
    'board.searchLabel': 'Search board',
    'board.searchPlaceholder': 'Search title, description, category, location',
    'board.sort': 'Sort',
    'board.sort.newest': 'Newest first',
    'board.sort.oldest': 'Oldest first',
    'board.sort.title': 'Title A–Z',
    'board.filter.status': 'Status',
    'board.filter.category': 'Category',
    'board.filter.location': 'Location',
    'board.filter.categoryAny': 'Any category',
    'board.filter.locationAny': 'Any location',
    'board.filter.withPhoto': 'With photo',
    'board.filter.verified': 'Verified',
    'board.status.all': 'All',
    'board.status.lost': 'Lost',
    'board.status.found': 'Found',
    'board.empty.noMatching': 'No matching reports',
    'board.empty.noReports': 'No reports yet',
    'board.empty.noMatchingSub': 'Try adjusting filters or clearing them to explore more reports.',
    'board.empty.noReportsSub': 'Reports will appear here once community members publish lost or found items.',
    'board.openDetails': 'Open details',
    'board.noPhoto': 'No photo',
    'board.justNow': 'Just now',
    'board.hoursAgo': '{{count}}h ago',
    'board.daysAgo': '{{count}}d ago',
    'status.verified': 'verified',
    'status.unverified': 'unverified',
    'item.back': '← Back to list',
'home.error.loadItems': 'Unable to load items right now. Please try again.',
    'new.authInitFailed': 'Could not initialize auth session.',
    'new.connectFirst': 'Connect Telegram first so ownership is server-side and synced with bot.',
    'new.created': 'Report created successfully. Redirecting...',
    'new.hero.title': 'Create a high-quality report',
    'new.hero.subtitle': 'Structured entry improves smart matching, moderation trust, and claim success rates.',
    'new.stats.completion': 'Completion',
    'new.stats.ownership': 'Ownership',
    'new.linked': 'Linked',
    'new.notLinked': 'Not linked',
    'new.form.title': 'Report form',
    'new.form.subtitle': 'Complete each block for the best match confidence.',
    'new.reportType': 'Report type',
    'new.title': 'Title',
    'new.suggested': 'Suggested category from title',
    'new.useSuggestion': 'Use suggestion',
    'new.description': 'Description',
    'new.contactName': 'Contact name',
    'new.telegramOptional': 'Telegram username (optional)',
    'new.photoOptional': 'Photo (optional)',
    'new.previewAlt': 'Selected preview',
    'new.create': 'Create report',
    'new.checklist.title': 'Submission checklist',
    'new.checklist.subtitle': 'Aim for high confidence matching.',
    'new.checklist.1': 'Clear title and category',
    'new.checklist.2': 'Exact location context',
    'new.checklist.3': 'Distinctive description details',
    'new.checklist.4': 'Photo for visual verification',
    'new.linkTelegram.title': 'Link Telegram',
    'new.linkTelegram.subtitle': 'Required for secure ownership and synced bot actions.',
    'new.linkTelegram.generate': 'Generate secure link code',
    'new.linkTelegram.refreshFailed': 'Could not refresh link status.',
    'new.linkTelegram.done': 'I linked my Telegram',
    'new.telegramLinked': 'Telegram linked',
    'new.telegramLinkedSub': 'You can submit and manage this report across web and bot.',
    'reports.title': 'Report control panel',
    'reports.subtitle': 'Manage lifecycle states, inbound claims, outbound claim requests, and account linking from a dashboard workspace.',
    'reports.stats.reports': 'Reports',
    'reports.stats.active': 'Active',
    'reports.stats.incoming': 'Incoming pending',
    'reports.stats.outgoing': 'Outgoing pending',
    'reports.connect.title': 'Connect Telegram',
    'reports.connect.subtitle': 'Required for secure ownership and synced web/bot workflows.',
    'reports.connect.generate': 'Generate link code',
    'reports.connect.send': 'Send this in Telegram:',
    'reports.my.title': 'My reports',
    'reports.my.subtitle': 'Your owned report inventory and lifecycle actions.',
    'reports.my.emptySub': 'Create a report to begin tracking lifecycle and claims.',
    'reports.my.create': 'Create report',
    'reports.resolve': 'Resolve',
    'reports.reopen': 'Reopen',
    'reports.delete': 'Delete',
    'reports.deleteConfirm': 'Delete this report permanently? This cannot be undone.',
    'reports.incomingTitle': 'Incoming claims',
    'reports.incomingSubtitle': 'Requests awaiting your decision.',
    'reports.incomingEmpty': 'No incoming claims.',
    'reports.outgoingTitle': 'Outgoing claims',
    'reports.outgoingSubtitle': 'Claims you initiated on matched items.',
    'reports.outgoingEmpty': 'No outgoing claims.',
    'reports.markReturned': 'Mark returned',
    'reports.contactsShared': 'Contacts shared',
    'reports.accountTitle': 'Connected account',
    'reports.signedInAs': 'Signed in as',
    'reports.unlink': 'Unlink Telegram',
    'reports.incomingUnavailable': 'Incoming claims unavailable.',
    'reports.outgoingUnavailable': 'Outgoing claims unavailable.',
    'reports.loadFailed': 'Failed to load dashboard. Please try again.',
    'reports.actionFailed': 'Action failed. Ensure this Telegram-linked account owns the report.',
    'item.workspace': 'report workspace',
    'item.heroSubtitle': 'Review status, evaluate smart matches, and manage claim handoff from one structured workspace.',
    'item.stats.lifecycle': 'Lifecycle',
    'item.stats.moderation': 'Moderation',
    'item.stats.verified': 'Verified',
    'item.stats.claims': 'Claims',
    'item.yes': 'Yes',
    'item.no': 'No',
    'item.overview.title': 'Report overview',
    'item.overview.subtitle': 'Core details and trust signals.',
    'item.hiddenUntilClaim': 'Hidden until approved claim',
    'item.hidden': 'Hidden',
    'item.contact': 'Contact',
    'item.matches.title': 'Smart matches',
    'item.matches.subtitle': 'Visual candidate board with immediate claim actions.',
    'item.matches.emptyTitle': 'No likely matches yet',
    'item.matches.emptySubtitle': 'New opposite-status reports will appear automatically.',
    'item.startClaim': 'Start claim handoff',
    'item.claim.startLoading': 'Starting…',
    'item.claim.startSuccess': 'Claim handoff request sent.',
    'item.claim.startFailed': 'Could not start claim handoff.',
    'item.claim.startState.pending': 'Claim already requested.',
    'item.claim.startState.approved': 'Claim already in active handoff.',
    'item.claim.startState.completed': 'This claim has already been completed.',
    'item.claim.startState.notMatch': 'This match was already marked as not matching.',
    'item.claim.startState.rejected': 'This claim was already rejected.',
    'item.claim.startState.cancelled': 'This claim was cancelled.',
    'item.claims.title': 'Claims & handoff',
    'item.claims.subtitle': 'Action queue for this report only.',
    'item.claims.empty': 'No claim requests yet.',
    'item.claim.label': 'Claim handoff',
    'item.claim.participant.source': 'Source report',
    'item.claim.participant.target': 'Matched report',
    'item.claim.address': 'Address',
    'item.claim.buildRouteSource': 'Build route (source)',
    'item.claim.buildRouteTarget': 'Build route (target)',
    'item.claim.shareLocation': 'Share current location',
    'item.claim.liveLocationLoading': 'Sharing location…',
    'item.claim.openLiveMeetup': 'Open live meetup',
    'item.claim.liveLocationUntil': 'Live location shared until {{until}}',
    'item.claim.liveLocationUnsupported': 'Geolocation is not supported in this browser.',
    'item.claim.liveLocationFailed': 'Could not share live location.',
    'item.claim.liveLocationShared': 'Live location shared.',
    'item.claim.returned': 'I returned the item',
    'item.claim.action.approve.success': 'Claim approved.',
    'item.claim.action.reject.success': 'Claim rejected.',
    'item.claim.action.complete.success': 'Handoff completed. Marked as returned.',
    'item.claim.status.pending': 'Pending',
    'item.claim.status.approved': 'Approved',
    'item.claim.status.rejected': 'Rejected',
    'item.claim.status.cancelled': 'Cancelled',
    'item.claim.status.completed': 'Completed',
    'item.claim.status.not_match': 'Not a match',
    'item.tab.overview': 'Overview',
    'item.tab.matches': 'Matches',
    'item.tab.claims': 'Claims & handoff',
    'item.close': 'Close',
    'item.image.expandedLabel': 'Expanded report image',
    'item.approve': 'Approve',
    'item.reject': 'Reject',
    'item.sharedContacts': 'Shared contacts',
    'item.telegram': 'Telegram',
    'item.lifecycle.active': 'Active',
    'item.lifecycle.resolved': 'Resolved',
    'item.lifecycle.deleted': 'Deleted',
    'item.moderation.pending': 'Pending',
    'item.moderation.approved': 'Approved',
    'item.moderation.rejected': 'Rejected',
    'item.moderation.flagged': 'Flagged',
    'item.safety.title': 'Safety',
    'item.safety.subtitle': 'Flag suspicious records for moderation.',
    'item.flagReport': 'Flag report',
    'item.flagged': 'Report flagged for admin review.',
'admin.verifyFailed': 'Could not verify admin access.',
    'admin.title': 'Operations moderation console',
    'admin.subtitle': 'Queue-first review with abuse signals, fast filters, and audit traceability.',
    'admin.stats.pending': 'Pending',
    'admin.stats.flagged': 'Flagged',
    'admin.stats.approved': 'Approved',
    'admin.stats.rejected': 'Rejected',
    'admin.stats.abuse': 'Abuse blocks 24h',
    'admin.partialWarning': 'Partial warning',
    'admin.connectFirst': 'Connect Telegram first',
    'admin.connectSub': 'Admin roles are bound to Telegram-linked identity.',
    'admin.sendBot': 'Send this to bot:',
    'admin.accessDenied': 'Access denied for',
    'admin.unknown': 'unknown',
    'admin.tabs.label': 'Moderation workspace tabs',
    'admin.tab.review': 'Review queue',
    'admin.tab.reports': 'Reports',
    'admin.tab.audit': 'Audit log',
    'admin.review.title': 'Review queue',
    'admin.review.subtitle': 'Role: {{role}}. Complaint-based moderation for flagged posts.',
    'admin.role.none': 'none',
    'admin.prevPage': 'Prev page',
    'admin.nextPage': 'Next page',
    'admin.offset': 'Offset: {{offset}}',
    'admin.loadingQueue': 'Loading queue…',
    'admin.selectedCount': 'Selected: {{count}}',
    'admin.selectAll': 'Select all visible',
    'admin.clearSelection': 'Clear selection',
    'admin.action.ignoreComplaint': 'Ignore complaint',
    'admin.action.deletePost': 'Delete post',
    'admin.action.ignoreComplaintSelected': 'Ignore complaint (selected)',
    'admin.action.deletePostSelected': 'Delete post (selected)',
    'admin.action.bulkIgnoreComplaint': 'Bulk ignore complaint',
    'admin.action.bulkDelete': 'Bulk delete',
    'admin.confirm.deleteSelected': 'Delete {{count}} selected posts?',
    'admin.confirm.deletePost': 'Delete post #{{id}}?',
    'admin.reports.title': 'Reports',
    'admin.reports.subtitle': 'Browse reports and handle complaints with minimal actions.',
    'admin.reports.emptyTitle': 'No reports in this queue',
    'admin.reports.emptySubtitle': 'Adjust filters to widen scope.',
    'admin.audit.title': 'Audit log',
    'admin.audit.subtitle': 'Review moderation history and filter by actor/item/date.',
    'admin.audit.eventType': 'Event type',
    'admin.audit.actor': 'Actor',
    'admin.audit.item': 'Item',
    'admin.audit.claim': 'Claim',
    'admin.audit.from': 'From',
    'admin.audit.to': 'To',
    'admin.audit.limit': 'Limit',
    'admin.audit.actorPlaceholder': 'Telegram ID',
    'admin.audit.itemPlaceholder': 'Item ID',
    'admin.audit.claimPlaceholder': 'Claim ID',
    'admin.audit.loading': 'Loading audit events…',
    'admin.audit.empty': 'No events found.',
    'admin.audit.meta': 'actor: {{actor}} · item: {{item}} · claim: {{claim}}',
    'admin.audit.filterItem': 'Filter item #{{id}}',
    'admin.audit.filterClaim': 'Filter claim #{{id}}',
    'admin.audit.details': 'Details',
    'admin.systemDetails': 'System details',
    'admin.system.highRisk': 'High-risk flagged (24h): {{count}}',
    'admin.system.stale': 'Stale complaints (48h): {{count}}',
    'admin.system.updating': 'Updating…',
    'admin.system.dupFlags': 'Duplicate flags 24h: {{count}}',
    'admin.system.dupClaims': 'Duplicate claims 24h: {{count}}',
    'admin.system.claimPressure': 'Claim pressure 24h: {{count}}',
    'admin.system.blockedQueries': 'Blocked audit queries 24h: {{count}}',
    'admin.system.runtime': 'Runtime: {{state}}',
    'admin.system.maintenance': 'Maintenance',
    'admin.system.maintenanceHealth': 'Maintenance health',
    'admin.filters.searchPlaceholder': 'Title/location/contact/user',
    'admin.filters.moderation': 'Moderation',
    'admin.filters.flaggedComplaints': 'Flagged complaints',
    'admin.filters.lifecycle': 'Lifecycle',
    'admin.filters.categoryPlaceholder': 'Exact category',
    'admin.filters.sort': 'Sort',
    'admin.filters.sort.created': 'Created',
    'admin.filters.sort.updated': 'Updated',
    'admin.filters.sort.moderated': 'Moderated',
    'admin.filters.sort.id': 'ID',
    'admin.filters.actorId': 'Actor ID',
    'admin.filters.actorPlaceholder': 'Owner Telegram ID',
    'admin.filters.verified': 'Verified',
    'admin.filters.verifiedOnly': 'Verified only',
    'admin.filters.unverifiedOnly': 'Unverified only',
    'admin.filters.order': 'Order',
    'admin.filters.orderDesc': 'Desc',
    'admin.filters.orderAsc': 'Asc',
    'admin.filters.pageSize': 'Page size',
    'admin.filters.suspiciousOnly': 'Suspicious only',
    'admin.filters.createdFrom': 'Created from',
    'admin.filters.createdTo': 'Created to',
    'admin.filters.advanced': 'Advanced filters',
    'admin.filters.apply': 'Apply filters',
    'admin.filters.loadQueue': 'Load queue',
    'admin.queue.empty': 'No reports in this queue.',
    'admin.queue.select': 'Select',
    'admin.preset.flagged': 'Flagged priority',
    'admin.preset.suspicious': 'Suspicious focus',
    'admin.signals.empty': 'No moderation signals yet.',
    'admin.signals.flags': 'Flags: {{total}} total · {{recent}} in 24h · duplicate pressure {{duplicate}}',
    'admin.signals.claims': 'Claims: {{total}} total · {{recent}} in 24h',
    'admin.signals.abuseBlocked': 'Blocked abuse actions (24h): {{count}}',
    'admin.signals.noMarkers': 'No active risk markers.',
    'admin.signals.highRisk': 'high risk',
    'admin.signals.marker.flagSpike24h': 'Flag spike in last 24h',
    'admin.signals.marker.highTotalFlags': 'High historical flag volume',
    'admin.signals.marker.claimSpike24h': 'Claim spike in last 24h',
    'admin.signals.marker.duplicatePressure': 'Repeated duplicate-flag pressure',
    'admin.signals.marker.abuseBlocks24h': 'Recent blocked abuse events',
    'reports.tabs.label': 'Reports workspace tabs',
    'reports.tab.my': 'My reports',
    'reports.tab.incoming': 'Incoming claims',
    'reports.tab.outgoing': 'Outgoing claims',
    'new.createFailed': 'Could not create item. Please review the form.',
    'new.savedAddress.use': 'Use saved profile address',
    'new.savedAddress.select': 'Select saved address',
    'new.category.other': 'Other',

    'reports.profileOnly': 'Manage Telegram connection in Profile.',
    'new.profileRequiredTitle': 'Link Telegram in Profile',
    'new.profileRequiredSubtitle': 'To create a report, go to Profile and register/link your Telegram account.',
    'new.profileHintTitle': 'Profile preferences help you fill faster',
    'new.profileHintSubtitle': 'Set display name, contact preference, and pickup location in Profile for quicker report creation.',
    'new.goProfile': 'Go to Profile',
    'profile.title': 'Profile',
    'profile.subtitle': 'Central place for Telegram linking, contact preferences, and pickup origin.',
    'profile.stats.telegram': 'Telegram',
    'profile.stats.language': 'Language',
    'profile.stats.theme': 'Theme',
    'profile.stats.role': 'Role',
    'profile.identity': 'Identity',
    'profile.identitySub': 'Avatar, display identity, and account status.',
    'profile.telegram': 'Telegram account',
    'profile.telegramSub': 'Manage secure website↔bot linking only here.',
    'profile.telegramUnlinked': 'Telegram is not linked yet.',
    'profile.telegramLinked': 'Telegram is linked and used for ownership syncing.',
    'profile.generateCode': 'Generate secure link code',
    'profile.generateCopy': 'Generate & Copy /link code',
    'profile.sendCode': 'Send this to Telegram bot:',
    'profile.copyCommand': 'Copy command',
    'profile.copied': 'Copied',
    'profile.copyFailed': 'Could not copy command.',
    'profile.linkDetected': 'Telegram linked successfully. Profile updated.',
    'profile.waitingForLink': 'Waiting for Telegram link…',
    'profile.unlink': 'Unlink Telegram',
    'profile.linked': 'Linked',
    'profile.unlinked': 'Unlinked',
    'profile.noUsername': 'Telegram username is not set',
    'profile.unknown': 'Unknown user',
    'profile.contactPrefs': 'Contact preferences',
    'profile.contactPrefsSub': 'These values are reused in web and bot report creation.',
    'profile.displayName': 'How should we address you?',
    'profile.contactMethod': 'Preferred contact method',
    'profile.contactDetails': 'Preferred contact details',
    'profile.contactPlaceholder': 'e.g. @username, +1..., email, or custom note',
    'profile.pickupLocation': 'Usual pickup origin / address',
    'profile.pickupPlaceholder': 'e.g. Dorm A lobby, Downtown station, etc.',
    'profile.save': 'Save profile',
    'profile.saved': 'Profile saved.',
    'profile.loadFailed': 'Could not load profile.',
    'profile.saveFailed': 'Could not save profile.',
    'profile.linkToEditTitle': 'Link Telegram to manage profile',
    'profile.linkToEditSub': 'After linking, you can save contact preferences used in report creation.',
  },
  ru: {
    'app.title': 'Бюро находок',
    'nav.items': 'Объявления',
    'nav.report': 'Создать объявление',
    'nav.myReports': 'Мои объявления',
    'nav.profile': 'Профиль',
    'nav.moderation': 'Модерация',
    'role.admin': 'Консоль администратора',
    'role.moderator': 'Консоль модератора',
    'settings.title': 'Настройки',
    'settings.subtitle': 'Персонализируйте оформление и язык',
    'settings.appearance': 'Оформление',
    'settings.theme': 'Тема',
    'settings.theme.light': 'Светлая',
    'settings.theme.dark': 'Тёмная',
    'settings.theme.system': 'Системная',
    'settings.language': 'Язык',
    'settings.language.en': 'English',
    'settings.language.ru': 'Русский',
    'common.loading': 'Загрузка…',
    'common.cancel': 'Отмена',
    'common.search': 'Поиск',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.reset': 'Сброс',
    'common.clearAll': 'Очистить всё',
    'common.filters': 'Фильтры',
    'common.hideFilters': 'Скрыть фильтры',
    'board.searchLabel': 'Поиск по объявлениям',
    'board.searchPlaceholder': 'Поиск по названию, описанию, категории, месту',
    'board.sort': 'Сортировка',
    'board.sort.newest': 'Сначала новые',
    'board.sort.oldest': 'Сначала старые',
    'board.sort.title': 'Название А–Я',
    'board.filter.status': 'Статус',
    'board.filter.category': 'Категория',
    'board.filter.location': 'Место',
    'board.filter.categoryAny': 'Любая категория',
    'board.filter.locationAny': 'Любое место',
    'board.filter.withPhoto': 'С фото',
    'board.filter.verified': 'Проверено',
    'board.status.all': 'Все',
    'board.status.lost': 'Потеряно',
    'board.status.found': 'Найдено',
    'board.empty.noMatching': 'Подходящих объявлений нет',
    'board.empty.noReports': 'Пока нет объявлений',
    'board.empty.noMatchingSub': 'Измените фильтры или очистите их, чтобы увидеть больше объявлений.',
    'board.empty.noReportsSub': 'Объявления появятся здесь, когда пользователи опубликуют потерянные или найденные вещи.',
    'board.openDetails': 'Открыть детали',
    'board.noPhoto': 'Нет фото',
    'board.justNow': 'Только что',
    'board.hoursAgo': '{{count}} ч назад',
    'board.daysAgo': '{{count}} дн. назад',
    'status.verified': 'проверено',
    'status.unverified': 'не проверено',
    'item.back': '← Назад к списку',
'home.error.loadItems': 'Сейчас не удалось загрузить объявления. Попробуйте снова.',
    'new.authInitFailed': 'Не удалось инициализировать сессию авторизации.',
    'new.connectFirst': 'Сначала подключите Telegram, чтобы владение объявлением синхронизировалось с ботом.',
    'new.created': 'Объявление создано. Выполняем переход…',
    'new.hero.title': 'Создайте качественное объявление',
    'new.hero.subtitle': 'Структурированное описание улучшает подбор совпадений и повышает доверие модерации.',
    'new.stats.completion': 'Заполнение',
    'new.stats.ownership': 'Владение',
    'new.linked': 'Подключено',
    'new.notLinked': 'Не подключено',
    'new.form.title': 'Форма объявления',
    'new.form.subtitle': 'Заполните все блоки для лучшего качества совпадений.',
    'new.reportType': 'Тип объявления',
    'new.title': 'Название',
    'new.suggested': 'Рекомендованная категория по названию',
    'new.useSuggestion': 'Использовать',
    'new.description': 'Описание',
    'new.contactName': 'Контактное имя',
    'new.telegramOptional': 'Имя пользователя Telegram (необязательно)',
    'new.photoOptional': 'Фото (необязательно)',
    'new.previewAlt': 'Предпросмотр',
    'new.create': 'Создать объявление',
    'new.checklist.title': 'Чеклист отправки',
    'new.checklist.subtitle': 'Стремитесь к высокому качеству совпадений.',
    'new.checklist.1': 'Понятное название и категория',
    'new.checklist.2': 'Точное место',
    'new.checklist.3': 'Подробное описание примет',
    'new.checklist.4': 'Фото для визуальной проверки',
    'new.linkTelegram.title': 'Привязка Telegram',
    'new.linkTelegram.subtitle': 'Нужна для безопасного владения и синхронизации с ботом.',
    'new.linkTelegram.generate': 'Сгенерировать код привязки',
    'new.linkTelegram.refreshFailed': 'Не удалось обновить статус привязки.',
    'new.linkTelegram.done': 'Я привязал Telegram',
    'new.telegramLinked': 'Telegram подключён',
    'new.telegramLinkedSub': 'Вы можете отправлять и управлять объявлением через веб и бота.',
    'reports.title': 'Панель управления объявлениями',
    'reports.subtitle': 'Управляйте жизненным циклом объявлений, заявками и привязкой аккаунта.',
    'reports.stats.reports': 'Объявления',
    'reports.stats.active': 'Активные',
    'reports.stats.incoming': 'Входящие в ожидании',
    'reports.stats.outgoing': 'Исходящие в ожидании',
    'reports.connect.title': 'Подключите Telegram',
    'reports.connect.subtitle': 'Нужно для безопасного владения и синхронизации веба с ботом.',
    'reports.connect.generate': 'Сгенерировать код',
    'reports.connect.send': 'Отправьте в Telegram:',
    'reports.my.title': 'Мои объявления',
    'reports.my.subtitle': 'Ваши объявления и действия по их жизненному циклу.',
    'reports.my.emptySub': 'Создайте объявление, чтобы начать отслеживание статусов и заявок.',
    'reports.my.create': 'Создать объявление',
    'reports.resolve': 'Завершить',
    'reports.reopen': 'Открыть снова',
    'reports.delete': 'Удалить',
    'reports.deleteConfirm': 'Удалить это объявление навсегда? Это действие нельзя отменить.',
    'reports.incomingTitle': 'Входящие заявки',
    'reports.incomingSubtitle': 'Запросы, ожидающие вашего решения.',
    'reports.incomingEmpty': 'Нет входящих заявок.',
    'reports.outgoingTitle': 'Исходящие заявки',
    'reports.outgoingSubtitle': 'Заявки, которые вы инициировали.',
    'reports.outgoingEmpty': 'Нет исходящих заявок.',
    'reports.markReturned': 'Отметить как возвращено',
    'reports.contactsShared': 'Контакты переданы',
    'reports.accountTitle': 'Подключённый аккаунт',
    'reports.signedInAs': 'Вход выполнен как',
    'reports.unlink': 'Отвязать Telegram',
    'reports.incomingUnavailable': 'Входящие заявки недоступны.',
    'reports.outgoingUnavailable': 'Исходящие заявки недоступны.',
    'reports.loadFailed': 'Не удалось загрузить панель. Попробуйте снова.',
    'reports.actionFailed': 'Операция не выполнена. Убедитесь, что этот Telegram-аккаунт владеет объявлением.',
    'item.workspace': 'рабочая область объявления',
    'item.heroSubtitle': 'Проверяйте статус, совпадения и управляйте передачей заявки в одном месте.',
    'item.stats.lifecycle': 'Жизненный цикл',
    'item.stats.moderation': 'Модерация',
    'item.stats.verified': 'Проверка',
    'item.stats.claims': 'Заявки',
    'item.yes': 'Да',
    'item.no': 'Нет',
    'item.overview.title': 'Обзор объявления',
    'item.overview.subtitle': 'Основные детали и сигналы доверия.',
    'item.hiddenUntilClaim': 'Скрыто до одобренной заявки',
    'item.hidden': 'Скрыто',
    'item.contact': 'Контакт',
    'item.matches.title': 'Умные совпадения',
    'item.matches.subtitle': 'Кандидаты для сопоставления и быстрые действия по заявке.',
    'item.matches.emptyTitle': 'Пока нет подходящих совпадений',
    'item.matches.emptySubtitle': 'Новые объявления противоположного типа появятся автоматически.',
    'item.startClaim': 'Начать передачу заявки',
    'item.claim.startLoading': 'Запуск…',
    'item.claim.startSuccess': 'Запрос на передачу заявки отправлен.',
    'item.claim.startFailed': 'Не удалось начать передачу заявки.',
    'item.claim.startState.pending': 'Заявка уже создана.',
    'item.claim.startState.approved': 'Заявка уже в активной передаче.',
    'item.claim.startState.completed': 'Эта заявка уже завершена.',
    'item.claim.startState.notMatch': 'Это совпадение уже отмечено как несовпадение.',
    'item.claim.startState.rejected': 'Эта заявка уже отклонена.',
    'item.claim.startState.cancelled': 'Эта заявка была отменена.',
    'item.claims.title': 'Заявки и передача',
    'item.claims.subtitle': 'Очередь действий только для этого объявления.',
    'item.claims.empty': 'Пока нет заявок.',
    'item.claim.label': 'Передача заявки',
    'item.claim.participant.source': 'Исходное объявление',
    'item.claim.participant.target': 'Совпавшее объявление',
    'item.claim.address': 'Адрес',
    'item.claim.buildRouteSource': 'Построить маршрут (источник)',
    'item.claim.buildRouteTarget': 'Построить маршрут (цель)',
    'item.claim.shareLocation': 'Поделиться текущей геопозицией',
    'item.claim.liveLocationLoading': 'Передаём геопозицию…',
    'item.claim.openLiveMeetup': 'Открыть live-встречу',
    'item.claim.liveLocationUntil': 'Геопозиция доступна до {{until}}',
    'item.claim.liveLocationUnsupported': 'Геолокация не поддерживается в этом браузере.',
    'item.claim.liveLocationFailed': 'Не удалось поделиться геопозицией.',
    'item.claim.liveLocationShared': 'Геопозиция опубликована.',
    'item.claim.returned': 'Я вернул(а) вещь',
    'item.claim.action.approve.success': 'Заявка одобрена.',
    'item.claim.action.reject.success': 'Заявка отклонена.',
    'item.claim.action.complete.success': 'Передача завершена. Возврат отмечен.',
    'item.claim.status.pending': 'Ожидает',
    'item.claim.status.approved': 'Одобрена',
    'item.claim.status.rejected': 'Отклонена',
    'item.claim.status.cancelled': 'Отменена',
    'item.claim.status.completed': 'Завершена',
    'item.claim.status.not_match': 'Не совпало',
    'item.tab.overview': 'Обзор',
    'item.tab.matches': 'Совпадения',
    'item.tab.claims': 'Заявки и передача',
    'item.close': 'Закрыть',
    'item.image.expandedLabel': 'Увеличенное изображение объявления',
    'item.approve': 'Одобрить',
    'item.reject': 'Отклонить',
    'item.sharedContacts': 'Общие контакты',
    'item.telegram': 'Telegram',
    'item.lifecycle.active': 'Активно',
    'item.lifecycle.resolved': 'Завершено',
    'item.lifecycle.deleted': 'Удалено',
    'item.moderation.pending': 'Ожидает',
    'item.moderation.approved': 'Одобрено',
    'item.moderation.rejected': 'Отклонено',
    'item.moderation.flagged': 'Помечено',
    'item.safety.title': 'Безопасность',
    'item.safety.subtitle': 'Пожалуйтесь на подозрительные записи для модерации.',
    'item.flagReport': 'Пожаловаться',
    'item.flagged': 'Объявление отправлено на проверку модератору.',
'admin.verifyFailed': 'Не удалось проверить права администратора.',
    'admin.title': 'Операционная консоль модерации',
    'admin.subtitle': 'Приоритетные очереди, сигналы злоупотреблений и прозрачный аудит.',
    'admin.stats.pending': 'Ожидают',
    'admin.stats.flagged': 'Помечены',
    'admin.stats.approved': 'Одобрены',
    'admin.stats.rejected': 'Отклонены',
    'admin.stats.abuse': 'Блокировок за 24ч',
    'admin.partialWarning': 'Частичное предупреждение',
    'admin.connectFirst': 'Сначала подключите Telegram',
    'admin.connectSub': 'Роли админа и модератора привязаны к Telegram-аккаунту.',
    'admin.sendBot': 'Отправьте боту:',
    'admin.accessDenied': 'Доступ запрещён для',
    'admin.unknown': 'неизвестно',
    'admin.tabs.label': 'Вкладки модерации',
    'admin.tab.review': 'Очередь проверки',
    'admin.tab.reports': 'Объявления',
    'admin.tab.audit': 'Аудит',
    'admin.review.title': 'Очередь проверки',
    'admin.review.subtitle': 'Роль: {{role}}. Жалобная модерация для помеченных объявлений.',
    'admin.role.none': 'нет',
    'admin.prevPage': 'Назад',
    'admin.nextPage': 'Вперёд',
    'admin.offset': 'Смещение: {{offset}}',
    'admin.loadingQueue': 'Загрузка очереди…',
    'admin.selectedCount': 'Выбрано: {{count}}',
    'admin.selectAll': 'Выбрать все видимые',
    'admin.clearSelection': 'Очистить выбор',
    'admin.action.ignoreComplaint': 'Игнорировать жалобу',
    'admin.action.deletePost': 'Удалить объявление',
    'admin.action.ignoreComplaintSelected': 'Игнорировать жалобу (выбранные)',
    'admin.action.deletePostSelected': 'Удалить объявление (выбранные)',
    'admin.action.bulkIgnoreComplaint': 'Массово: игнорировать жалобу',
    'admin.action.bulkDelete': 'Массово: удалить',
    'admin.confirm.deleteSelected': 'Удалить {{count}} выбранных объявлений?',
    'admin.confirm.deletePost': 'Удалить объявление #{{id}}?',
    'admin.reports.title': 'Объявления',
    'admin.reports.subtitle': 'Просматривайте объявления и обрабатывайте жалобы без лишних действий.',
    'admin.reports.emptyTitle': 'В этой очереди нет объявлений',
    'admin.reports.emptySubtitle': 'Измените фильтры, чтобы расширить выборку.',
    'admin.audit.title': 'Журнал аудита',
    'admin.audit.subtitle': 'История модерации с фильтрами по участнику, объявлению и дате.',
    'admin.audit.eventType': 'Тип события',
    'admin.audit.actor': 'Участник',
    'admin.audit.item': 'Объявление',
    'admin.audit.claim': 'Заявка',
    'admin.audit.from': 'С',
    'admin.audit.to': 'По',
    'admin.audit.limit': 'Лимит',
    'admin.audit.actorPlaceholder': 'ID Telegram',
    'admin.audit.itemPlaceholder': 'ID объявления',
    'admin.audit.claimPlaceholder': 'ID заявки',
    'admin.audit.loading': 'Загрузка событий аудита…',
    'admin.audit.empty': 'События не найдены.',
    'admin.audit.meta': 'участник: {{actor}} · объявление: {{item}} · заявка: {{claim}}',
    'admin.audit.filterItem': 'Фильтр по объявлению #{{id}}',
    'admin.audit.filterClaim': 'Фильтр по заявке #{{id}}',
    'admin.audit.details': 'Детали',
    'admin.systemDetails': 'Системные детали',
    'admin.system.highRisk': 'Высокорисковых флагов (24ч): {{count}}',
    'admin.system.stale': 'Застарелых жалоб (48ч): {{count}}',
    'admin.system.updating': 'Обновляем…',
    'admin.system.dupFlags': 'Дубликатов жалоб за 24ч: {{count}}',
    'admin.system.dupClaims': 'Дубликатов заявок за 24ч: {{count}}',
    'admin.system.claimPressure': 'Давление заявок за 24ч: {{count}}',
    'admin.system.blockedQueries': 'Блокировок audit-запросов за 24ч: {{count}}',
    'admin.system.runtime': 'Рантайм: {{state}}',
    'admin.system.maintenance': 'Обслуживание',
    'admin.system.maintenanceHealth': 'Здоровье обслуживания',
    'admin.filters.searchPlaceholder': 'Название/место/контакт/пользователь',
    'admin.filters.moderation': 'Модерация',
    'admin.filters.flaggedComplaints': 'Помеченные жалобы',
    'admin.filters.lifecycle': 'Жизненный цикл',
    'admin.filters.categoryPlaceholder': 'Точная категория',
    'admin.filters.sort': 'Сортировка',
    'admin.filters.sort.created': 'Создано',
    'admin.filters.sort.updated': 'Обновлено',
    'admin.filters.sort.moderated': 'Модерировано',
    'admin.filters.sort.id': 'ID',
    'admin.filters.actorId': 'ID участника',
    'admin.filters.actorPlaceholder': 'ID владельца в Telegram',
    'admin.filters.verified': 'Проверка',
    'admin.filters.verifiedOnly': 'Только проверенные',
    'admin.filters.unverifiedOnly': 'Только непроверенные',
    'admin.filters.order': 'Порядок',
    'admin.filters.orderDesc': 'По убыванию',
    'admin.filters.orderAsc': 'По возрастанию',
    'admin.filters.pageSize': 'Размер страницы',
    'admin.filters.suspiciousOnly': 'Только подозрительные',
    'admin.filters.createdFrom': 'Создано с',
    'admin.filters.createdTo': 'Создано по',
    'admin.filters.advanced': 'Расширенные фильтры',
    'admin.filters.apply': 'Применить фильтры',
    'admin.filters.loadQueue': 'Загрузить очередь',
    'admin.queue.empty': 'В этой очереди нет объявлений.',
    'admin.queue.select': 'Выбрать',
    'admin.preset.flagged': 'Приоритет по жалобам',
    'admin.preset.suspicious': 'Фокус на рисках',
    'admin.signals.empty': 'Пока нет сигналов модерации.',
    'admin.signals.flags': 'Жалобы: всего {{total}} · за 24ч {{recent}} · давление дублей {{duplicate}}',
    'admin.signals.claims': 'Заявки: всего {{total}} · за 24ч {{recent}}',
    'admin.signals.abuseBlocked': 'Заблокированных злоупотреблений (24ч): {{count}}',
    'admin.signals.noMarkers': 'Активных маркеров риска нет.',
    'admin.signals.highRisk': 'высокий риск',
    'admin.signals.marker.flagSpike24h': 'Всплеск жалоб за 24ч',
    'admin.signals.marker.highTotalFlags': 'Высокий исторический объём жалоб',
    'admin.signals.marker.claimSpike24h': 'Всплеск заявок за 24ч',
    'admin.signals.marker.duplicatePressure': 'Повторяющееся давление дубликатами жалоб',
    'admin.signals.marker.abuseBlocks24h': 'Недавние блокировки злоупотреблений',
    'reports.tabs.label': 'Вкладки панели объявлений',
    'reports.tab.my': 'Мои объявления',
    'reports.tab.incoming': 'Входящие заявки',
    'reports.tab.outgoing': 'Исходящие заявки',
    'new.createFailed': 'Не удалось создать объявление. Проверьте форму.',
    'new.savedAddress.use': 'Использовать сохранённый адрес профиля',
    'new.savedAddress.select': 'Выберите сохранённый адрес',
    'new.category.other': 'Другое',

    'reports.profileOnly': 'Управляйте подключением Telegram только в Профиле.',
    'new.profileRequiredTitle': 'Подключите Telegram в Профиле',
    'new.profileRequiredSubtitle': 'Чтобы создать объявление, перейдите в Профиль и зарегистрируйте/привяжите Telegram.',
    'new.profileHintTitle': 'Профиль помогает заполнять быстрее',
    'new.profileHintSubtitle': 'Укажите имя, контакты и обычное место в Профиле для быстрого создания объявлений.',
    'new.goProfile': 'Открыть Профиль',
    'profile.title': 'Профиль',
    'profile.subtitle': 'Единое место для привязки Telegram, контактных предпочтений и адреса/точки выдачи.',
    'profile.stats.telegram': 'Telegram',
    'profile.stats.language': 'Язык',
    'profile.stats.theme': 'Тема',
    'profile.stats.role': 'Роль',
    'profile.identity': 'Личность',
    'profile.identitySub': 'Аватар, отображаемое имя и статус аккаунта.',
    'profile.telegram': 'Telegram-аккаунт',
    'profile.telegramSub': 'Управляйте безопасной связкой сайт↔бот только здесь.',
    'profile.telegramUnlinked': 'Telegram пока не подключён.',
    'profile.telegramLinked': 'Telegram подключён и используется для синхронизации владения.',
    'profile.generateCode': 'Сгенерировать безопасный код',
    'profile.generateCopy': 'Создать и скопировать /link код',
    'profile.sendCode': 'Отправьте это боту в Telegram:',
    'profile.copyCommand': 'Скопировать команду',
    'profile.copied': 'Скопировано',
    'profile.copyFailed': 'Не удалось скопировать команду.',
    'profile.linkDetected': 'Telegram успешно подключён. Профиль обновлён.',
    'profile.waitingForLink': 'Ожидание привязки в Telegram…',
    'profile.unlink': 'Отвязать Telegram',
    'profile.linked': 'Подключено',
    'profile.unlinked': 'Не подключено',
    'profile.noUsername': 'Имя пользователя Telegram не задано',
    'profile.unknown': 'Неизвестный пользователь',
    'profile.contactPrefs': 'Контактные предпочтения',
    'profile.contactPrefsSub': 'Эти значения переиспользуются при создании объявлений на сайте и в боте.',
    'profile.displayName': 'Как к вам обращаться?',
    'profile.contactMethod': 'Предпочитаемый способ связи',
    'profile.contactDetails': 'Предпочитаемые контакты',
    'profile.contactPlaceholder': 'например @username, +7..., email или свой текст',
    'profile.pickupLocation': 'Обычное место/адрес выдачи',
    'profile.pickupPlaceholder': 'например Вестибюль общежития, станция Центр и т.п.',
    'profile.save': 'Сохранить профиль',
    'profile.saved': 'Профиль сохранён.',
    'profile.loadFailed': 'Не удалось загрузить профиль.',
    'profile.saveFailed': 'Не удалось сохранить профиль.',
    'profile.linkToEditTitle': 'Подключите Telegram для управления профилем',
    'profile.linkToEditSub': 'После подключения вы сможете сохранить контактные настройки для создания объявлений.',
  },
}

type SettingsContextValue = {
  theme: ThemeMode
  language: Language
  resolvedTheme: 'light' | 'dark'
  setTheme: (value: ThemeMode) => void
  setLanguage: (value: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const SettingsContext = createContext<SettingsContextValue | undefined>(undefined)

const interpolate = (template: string, params?: Record<string, string | number>) => {
  if (!params) return template
  return Object.entries(params).reduce((acc, [key, value]) => acc.split(`{{${key}}}`).join(String(value)), template)
}

const systemTheme = () => (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')

export const SettingsProvider = ({ children }: { children: ReactNode }) => {
  const [theme, setTheme] = useState<ThemeMode>(() => (localStorage.getItem(STORAGE_THEME) as ThemeMode) || 'system')
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem(STORAGE_LANGUAGE) as Language) || 'en')
  const [resolvedTheme, setResolvedTheme] = useState<'light' | 'dark'>(() => (typeof window === 'undefined' ? 'light' : systemTheme()))

  useEffect(() => {
    localStorage.setItem(STORAGE_THEME, theme)
  }, [theme])

  useEffect(() => {
    localStorage.setItem(STORAGE_LANGUAGE, language)
  }, [language])

  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)')
    const apply = () => {
      const next = theme === 'system' ? systemTheme() : theme
      setResolvedTheme(next)
      document.documentElement.setAttribute('data-theme', next)
    }

    apply()
    media.addEventListener('change', apply)
    return () => media.removeEventListener('change', apply)
  }, [theme])

  const value = useMemo<SettingsContextValue>(() => ({
    theme,
    language,
    resolvedTheme,
    setTheme,
    setLanguage,
    t: (key, params) => {
      const template = translations[language][key] ?? translations.en[key] ?? key
      return interpolate(template, params)
    },
  }), [theme, language, resolvedTheme])

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>
}

export const useSettings = () => {
  const value = useContext(SettingsContext)
  if (!value) {
    throw new Error('useSettings must be used within SettingsProvider')
  }
  return value
}
