import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react'

export type ThemeMode = 'light' | 'dark' | 'system'
export type Language = 'en' | 'ru'

type TranslationDict = Record<string, string>

const STORAGE_THEME = 'lfb:theme'
const STORAGE_LANGUAGE = 'lfb:language'

const translations: Record<Language, TranslationDict> = {
  en: {
    'app.title': 'Lost & Found Board',
    'nav.items': 'Items',
    'nav.report': 'Report Item',
    'nav.myReports': 'My Reports',
    'nav.profile': 'Profile',
    'nav.moderation': 'Moderation',
    'role.admin': 'Admin Console',
    'role.moderator': 'Moderator Console',
    'settings.title': 'Settings',
    'settings.subtitle': 'Personalize appearance and language',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.system': 'System',
    'settings.language': 'Language',
    'settings.language.en': 'English',
    'settings.language.ru': 'Русский',
    'common.loading': 'Loading…',
    'common.cancel': 'Cancel',
    'common.search': 'Search',
    'common.reset': 'Reset',
    'common.clearAll': 'Clear all',
    'common.filters': 'Filters',
    'common.hideFilters': 'Hide filters',
    'board.searchLabel': 'Search board',
    'board.searchPlaceholder': 'Search title, description, category, location',
    'board.sort': 'Sort',
    'board.sort.newest': 'Newest first',
    'board.sort.oldest': 'Oldest first',
    'board.sort.title': 'Title A–Z',
    'board.filter.status': 'Status',
    'board.filter.category': 'Category',
    'board.filter.location': 'Location',
    'board.filter.categoryAny': 'Any category',
    'board.filter.locationAny': 'Any location',
    'board.filter.withPhoto': 'With photo',
    'board.filter.verified': 'Verified',
    'board.status.all': 'All',
    'board.status.lost': 'Lost',
    'board.status.found': 'Found',
    'board.empty.noMatching': 'No matching reports',
    'board.empty.noReports': 'No reports yet',
    'board.empty.noMatchingSub': 'Try adjusting filters or clearing them to explore more reports.',
    'board.empty.noReportsSub': 'Reports will appear here once community members publish lost or found items.',
    'board.openDetails': 'Open details',
    'board.noPhoto': 'No photo',
    'board.justNow': 'Just now',
    'board.hoursAgo': '{{count}}h ago',
    'board.daysAgo': '{{count}}d ago',
    'status.verified': 'verified',
    'status.unverified': 'unverified',
    'item.back': '← Back to list',
'home.error.loadItems': 'Unable to load items right now. Please try again.',
    'new.authInitFailed': 'Could not initialize auth session.',
    'new.connectFirst': 'Connect Telegram first so ownership is server-side and synced with bot.',
    'new.created': 'Report created successfully. Redirecting...',
    'new.hero.title': 'Create a high-quality report',
    'new.hero.subtitle': 'Structured entry improves smart matching, moderation trust, and claim success rates.',
    'new.stats.completion': 'Completion',
    'new.stats.ownership': 'Ownership',
    'new.linked': 'Linked',
    'new.notLinked': 'Not linked',
    'new.form.title': 'Report form',
    'new.form.subtitle': 'Complete each block for the best match confidence.',
    'new.reportType': 'Report type',
    'new.title': 'Title',
    'new.suggested': 'Suggested category from title',
    'new.useSuggestion': 'Use suggestion',
    'new.description': 'Description',
    'new.contactName': 'Contact name',
    'new.telegramOptional': 'Telegram username (optional)',
    'new.photoOptional': 'Photo (optional)',
    'new.previewAlt': 'Selected preview',
    'new.create': 'Create report',
    'new.checklist.title': 'Submission checklist',
    'new.checklist.subtitle': 'Aim for high confidence matching.',
    'new.checklist.1': 'Clear title and category',
    'new.checklist.2': 'Exact location context',
    'new.checklist.3': 'Distinctive description details',
    'new.checklist.4': 'Photo for visual verification',
    'new.linkTelegram.title': 'Link Telegram',
    'new.linkTelegram.subtitle': 'Required for secure ownership and synced bot actions.',
    'new.linkTelegram.generate': 'Generate secure link code',
    'new.linkTelegram.refreshFailed': 'Could not refresh link status.',
    'new.linkTelegram.done': 'I linked my Telegram',
    'new.telegramLinked': 'Telegram linked',
    'new.telegramLinkedSub': 'You can submit and manage this report across web and bot.',
    'reports.title': 'Report control panel',
    'reports.subtitle': 'Manage lifecycle states, inbound claims, outbound claim requests, and account linking from a dashboard workspace.',
    'reports.stats.reports': 'Reports',
    'reports.stats.active': 'Active',
    'reports.stats.incoming': 'Incoming pending',
    'reports.stats.outgoing': 'Outgoing pending',
    'reports.connect.title': 'Connect Telegram',
    'reports.connect.subtitle': 'Required for secure ownership and synced web/bot workflows.',
    'reports.connect.generate': 'Generate link code',
    'reports.connect.send': 'Send this in Telegram:',
    'reports.my.title': 'My reports',
    'reports.my.subtitle': 'Your owned report inventory and lifecycle actions.',
    'reports.my.emptySub': 'Create a report to begin tracking lifecycle and claims.',
    'reports.my.create': 'Create report',
    'reports.resolve': 'Resolve',
    'reports.reopen': 'Reopen',
    'reports.delete': 'Delete',
    'reports.incomingTitle': 'Incoming claims',
    'reports.incomingSubtitle': 'Requests awaiting your decision.',
    'reports.incomingEmpty': 'No incoming claims.',
    'reports.outgoingTitle': 'Outgoing claims',
    'reports.outgoingSubtitle': 'Claims you initiated on matched items.',
    'reports.outgoingEmpty': 'No outgoing claims.',
    'reports.markReturned': 'Mark returned',
    'reports.contactsShared': 'Contacts shared',
    'reports.accountTitle': 'Connected account',
    'reports.signedInAs': 'Signed in as',
    'reports.unlink': 'Unlink Telegram',
    'reports.incomingUnavailable': 'Incoming claims unavailable.',
    'reports.outgoingUnavailable': 'Outgoing claims unavailable.',
    'reports.loadFailed': 'Failed to load dashboard. Please try again.',
    'reports.actionFailed': 'Action failed. Ensure this Telegram-linked account owns the report.',
    'item.workspace': 'report workspace',
    'item.heroSubtitle': 'Review status, evaluate smart matches, and manage claim handoff from one structured workspace.',
    'item.stats.lifecycle': 'Lifecycle',
    'item.stats.moderation': 'Moderation',
    'item.stats.verified': 'Verified',
    'item.stats.claims': 'Claims',
    'item.yes': 'Yes',
    'item.no': 'No',
    'item.overview.title': 'Report overview',
    'item.overview.subtitle': 'Core details and trust signals.',
    'item.hiddenUntilClaim': 'Hidden until approved claim',
    'item.hidden': 'Hidden',
    'item.contact': 'Contact',
    'item.matches.title': 'Smart matches',
    'item.matches.subtitle': 'Visual candidate board with immediate claim actions.',
    'item.matches.emptyTitle': 'No likely matches yet',
    'item.matches.emptySubtitle': 'New opposite-status reports will appear automatically.',
    'item.startClaim': 'Start claim handoff',
    'item.claims.title': 'Claims & handoff',
    'item.claims.subtitle': 'Action queue for this report only.',
    'item.claims.empty': 'No claim requests yet.',
    'item.approve': 'Approve',
    'item.reject': 'Reject',
    'item.sharedContacts': 'Shared contacts',
    'item.safety.title': 'Safety',
    'item.safety.subtitle': 'Flag suspicious records for moderation.',
    'item.flagReport': 'Flag report',
    'item.flagged': 'Report flagged for admin review.',
'admin.verifyFailed': 'Could not verify admin access.',
    'admin.title': 'Operations moderation console',
    'admin.subtitle': 'Queue-first review with abuse signals, fast filters, and audit traceability.',
    'admin.stats.pending': 'Pending',
    'admin.stats.flagged': 'Flagged',
    'admin.stats.approved': 'Approved',
    'admin.stats.rejected': 'Rejected',
    'admin.stats.abuse': 'Abuse blocks 24h',
    'admin.partialWarning': 'Partial warning',
    'admin.connectFirst': 'Connect Telegram first',
    'admin.connectSub': 'Admin roles are bound to Telegram-linked identity.',
    'admin.sendBot': 'Send this to bot:',
    'admin.accessDenied': 'Access denied for',

    'reports.profileOnly': 'Manage Telegram connection in Profile.',
    'new.profileRequiredTitle': 'Telegram linking moved to Profile',
    'new.profileRequiredSubtitle': 'To create reports with secure ownership, connect Telegram in your Profile page.',
    'new.profileHintTitle': 'Profile preferences help you fill faster',
    'new.profileHintSubtitle': 'Set display name, contact preference, and pickup location in Profile for quicker report creation.',
    'new.goProfile': 'Go to Profile',
    'profile.title': 'Profile',
    'profile.subtitle': 'Central place for Telegram linking, contact preferences, and pickup origin.',
    'profile.stats.telegram': 'Telegram',
    'profile.stats.language': 'Language',
    'profile.stats.theme': 'Theme',
    'profile.stats.role': 'Role',
    'profile.identity': 'Identity',
    'profile.identitySub': 'Avatar, display identity, and account status.',
    'profile.telegram': 'Telegram account',
    'profile.telegramSub': 'Manage secure website↔bot linking only here.',
    'profile.telegramUnlinked': 'Telegram is not linked yet.',
    'profile.telegramLinked': 'Telegram is linked and used for ownership syncing.',
    'profile.generateCode': 'Generate secure link code',
    'profile.generateCopy': 'Generate & Copy /link code',
    'profile.sendCode': 'Send this to Telegram bot:',
    'profile.copyCommand': 'Copy command',
    'profile.copied': 'Copied',
    'profile.copyFailed': 'Could not copy command.',
    'profile.linkDetected': 'Telegram linked successfully. Profile updated.',
    'profile.waitingForLink': 'Waiting for Telegram link…',
    'profile.unlink': 'Unlink Telegram',
    'profile.linked': 'Linked',
    'profile.unlinked': 'Unlinked',
    'profile.noUsername': 'Telegram username is not set',
    'profile.unknown': 'Unknown user',
    'profile.contactPrefs': 'Contact preferences',
    'profile.contactPrefsSub': 'These values are reused in web and bot report creation.',
    'profile.displayName': 'How should we address you?',
    'profile.contactMethod': 'Preferred contact method',
    'profile.contactDetails': 'Preferred contact details',
    'profile.contactPlaceholder': 'e.g. @username, +1..., email, or custom note',
    'profile.pickupLocation': 'Usual pickup origin / address',
    'profile.pickupPlaceholder': 'e.g. Dorm A lobby, Downtown station, etc.',
    'profile.save': 'Save profile',
    'profile.saved': 'Profile saved.',
    'profile.loadFailed': 'Could not load profile.',
    'profile.saveFailed': 'Could not save profile.',
    'profile.linkToEditTitle': 'Link Telegram to manage profile',
    'profile.linkToEditSub': 'After linking, you can save contact preferences used in report creation.',
  },
  ru: {
    'app.title': 'Бюро находок',
    'nav.items': 'Объявления',
    'nav.report': 'Сообщить о вещи',
    'nav.myReports': 'Мои объявления',
    'nav.profile': 'Профиль',
    'nav.moderation': 'Модерация',
    'role.admin': 'Консоль администратора',
    'role.moderator': 'Консоль модератора',
    'settings.title': 'Настройки',
    'settings.subtitle': 'Персонализируйте оформление и язык',
    'settings.appearance': 'Оформление',
    'settings.theme': 'Тема',
    'settings.theme.light': 'Светлая',
    'settings.theme.dark': 'Тёмная',
    'settings.theme.system': 'Системная',
    'settings.language': 'Язык',
    'settings.language.en': 'English',
    'settings.language.ru': 'Русский',
    'common.loading': 'Загрузка…',
    'common.cancel': 'Отмена',
    'common.search': 'Поиск',
    'common.reset': 'Сброс',
    'common.clearAll': 'Очистить всё',
    'common.filters': 'Фильтры',
    'common.hideFilters': 'Скрыть фильтры',
    'board.searchLabel': 'Поиск по объявлениям',
    'board.searchPlaceholder': 'Поиск по названию, описанию, категории, месту',
    'board.sort': 'Сортировка',
    'board.sort.newest': 'Сначала новые',
    'board.sort.oldest': 'Сначала старые',
    'board.sort.title': 'Название А–Я',
    'board.filter.status': 'Статус',
    'board.filter.category': 'Категория',
    'board.filter.location': 'Место',
    'board.filter.categoryAny': 'Любая категория',
    'board.filter.locationAny': 'Любое место',
    'board.filter.withPhoto': 'С фото',
    'board.filter.verified': 'Проверено',
    'board.status.all': 'Все',
    'board.status.lost': 'Потеряно',
    'board.status.found': 'Найдено',
    'board.empty.noMatching': 'Подходящих объявлений нет',
    'board.empty.noReports': 'Пока нет объявлений',
    'board.empty.noMatchingSub': 'Измените фильтры или очистите их, чтобы увидеть больше объявлений.',
    'board.empty.noReportsSub': 'Объявления появятся здесь, когда пользователи опубликуют потерянные или найденные вещи.',
    'board.openDetails': 'Открыть детали',
    'board.noPhoto': 'Нет фото',
    'board.justNow': 'Только что',
    'board.hoursAgo': '{{count}} ч назад',
    'board.daysAgo': '{{count}} дн. назад',
    'status.verified': 'проверено',
    'status.unverified': 'не проверено',
    'item.back': '← Назад к списку',
'home.error.loadItems': 'Сейчас не удалось загрузить объявления. Попробуйте снова.',
    'new.authInitFailed': 'Не удалось инициализировать сессию авторизации.',
    'new.connectFirst': 'Сначала подключите Telegram, чтобы владение объявлением синхронизировалось с ботом.',
    'new.created': 'Объявление создано. Выполняем переход…',
    'new.hero.title': 'Создайте качественное объявление',
    'new.hero.subtitle': 'Структурированное описание улучшает подбор совпадений и повышает доверие модерации.',
    'new.stats.completion': 'Заполнение',
    'new.stats.ownership': 'Владение',
    'new.linked': 'Подключено',
    'new.notLinked': 'Не подключено',
    'new.form.title': 'Форма объявления',
    'new.form.subtitle': 'Заполните все блоки для лучшего качества совпадений.',
    'new.reportType': 'Тип объявления',
    'new.title': 'Название',
    'new.suggested': 'Рекомендованная категория по названию',
    'new.useSuggestion': 'Использовать',
    'new.description': 'Описание',
    'new.contactName': 'Контактное имя',
    'new.telegramOptional': 'Имя пользователя Telegram (необязательно)',
    'new.photoOptional': 'Фото (необязательно)',
    'new.previewAlt': 'Предпросмотр',
    'new.create': 'Создать объявление',
    'new.checklist.title': 'Чеклист отправки',
    'new.checklist.subtitle': 'Стремитесь к высокому качеству совпадений.',
    'new.checklist.1': 'Понятное название и категория',
    'new.checklist.2': 'Точное место',
    'new.checklist.3': 'Подробное описание примет',
    'new.checklist.4': 'Фото для визуальной проверки',
    'new.linkTelegram.title': 'Привязка Telegram',
    'new.linkTelegram.subtitle': 'Нужна для безопасного владения и синхронизации с ботом.',
    'new.linkTelegram.generate': 'Сгенерировать код привязки',
    'new.linkTelegram.refreshFailed': 'Не удалось обновить статус привязки.',
    'new.linkTelegram.done': 'Я привязал Telegram',
    'new.telegramLinked': 'Telegram подключён',
    'new.telegramLinkedSub': 'Вы можете отправлять и управлять объявлением через веб и бота.',
    'reports.title': 'Панель управления объявлениями',
    'reports.subtitle': 'Управляйте жизненным циклом объявлений, заявками и привязкой аккаунта.',
    'reports.stats.reports': 'Объявления',
    'reports.stats.active': 'Активные',
    'reports.stats.incoming': 'Входящие в ожидании',
    'reports.stats.outgoing': 'Исходящие в ожидании',
    'reports.connect.title': 'Подключите Telegram',
    'reports.connect.subtitle': 'Нужно для безопасного владения и синхронизации веба с ботом.',
    'reports.connect.generate': 'Сгенерировать код',
    'reports.connect.send': 'Отправьте в Telegram:',
    'reports.my.title': 'Мои объявления',
    'reports.my.subtitle': 'Ваши объявления и действия по их жизненному циклу.',
    'reports.my.emptySub': 'Создайте объявление, чтобы начать отслеживание статусов и заявок.',
    'reports.my.create': 'Создать объявление',
    'reports.resolve': 'Завершить',
    'reports.reopen': 'Открыть снова',
    'reports.delete': 'Удалить',
    'reports.incomingTitle': 'Входящие заявки',
    'reports.incomingSubtitle': 'Запросы, ожидающие вашего решения.',
    'reports.incomingEmpty': 'Нет входящих заявок.',
    'reports.outgoingTitle': 'Исходящие заявки',
    'reports.outgoingSubtitle': 'Заявки, которые вы инициировали.',
    'reports.outgoingEmpty': 'Нет исходящих заявок.',
    'reports.markReturned': 'Отметить как возвращено',
    'reports.contactsShared': 'Контакты переданы',
    'reports.accountTitle': 'Подключённый аккаунт',
    'reports.signedInAs': 'Вход выполнен как',
    'reports.unlink': 'Отвязать Telegram',
    'reports.incomingUnavailable': 'Входящие заявки недоступны.',
    'reports.outgoingUnavailable': 'Исходящие заявки недоступны.',
    'reports.loadFailed': 'Не удалось загрузить панель. Попробуйте снова.',
    'reports.actionFailed': 'Операция не выполнена. Убедитесь, что этот Telegram-аккаунт владеет объявлением.',
    'item.workspace': 'рабочая область объявления',
    'item.heroSubtitle': 'Проверяйте статус, совпадения и управляйте передачей заявки в одном месте.',
    'item.stats.lifecycle': 'Жизненный цикл',
    'item.stats.moderation': 'Модерация',
    'item.stats.verified': 'Проверка',
    'item.stats.claims': 'Заявки',
    'item.yes': 'Да',
    'item.no': 'Нет',
    'item.overview.title': 'Обзор объявления',
    'item.overview.subtitle': 'Основные детали и сигналы доверия.',
    'item.hiddenUntilClaim': 'Скрыто до одобренной заявки',
    'item.hidden': 'Скрыто',
    'item.contact': 'Контакт',
    'item.matches.title': 'Умные совпадения',
    'item.matches.subtitle': 'Кандидаты для сопоставления и быстрые действия по заявке.',
    'item.matches.emptyTitle': 'Пока нет подходящих совпадений',
    'item.matches.emptySubtitle': 'Новые объявления противоположного типа появятся автоматически.',
    'item.startClaim': 'Начать передачу заявки',
    'item.claims.title': 'Заявки и передача',
    'item.claims.subtitle': 'Очередь действий только для этого объявления.',
    'item.claims.empty': 'Пока нет заявок.',
    'item.approve': 'Одобрить',
    'item.reject': 'Отклонить',
    'item.sharedContacts': 'Общие контакты',
    'item.safety.title': 'Безопасность',
    'item.safety.subtitle': 'Пожалуйтесь на подозрительные записи для модерации.',
    'item.flagReport': 'Пожаловаться',
    'item.flagged': 'Объявление отправлено на проверку модератору.',
'admin.verifyFailed': 'Не удалось проверить права администратора.',
    'admin.title': 'Операционная консоль модерации',
    'admin.subtitle': 'Приоритетные очереди, сигналы злоупотреблений и прозрачный аудит.',
    'admin.stats.pending': 'Ожидают',
    'admin.stats.flagged': 'Помечены',
    'admin.stats.approved': 'Одобрены',
    'admin.stats.rejected': 'Отклонены',
    'admin.stats.abuse': 'Блокировок за 24ч',
    'admin.partialWarning': 'Частичное предупреждение',
    'admin.connectFirst': 'Сначала подключите Telegram',
    'admin.connectSub': 'Роли админа и модератора привязаны к Telegram-аккаунту.',
    'admin.sendBot': 'Отправьте боту:',
    'admin.accessDenied': 'Доступ запрещён для',

    'reports.profileOnly': 'Управляйте подключением Telegram только в Профиле.',
    'new.profileRequiredTitle': 'Привязка Telegram перенесена в Профиль',
    'new.profileRequiredSubtitle': 'Чтобы создавать объявления с защищённым владением, подключите Telegram на странице Профиля.',
    'new.profileHintTitle': 'Профиль помогает заполнять быстрее',
    'new.profileHintSubtitle': 'Укажите имя, контакты и обычное место в Профиле для быстрого создания объявлений.',
    'new.goProfile': 'Открыть Профиль',
    'profile.title': 'Профиль',
    'profile.subtitle': 'Единое место для привязки Telegram, контактных предпочтений и адреса/точки выдачи.',
    'profile.stats.telegram': 'Telegram',
    'profile.stats.language': 'Язык',
    'profile.stats.theme': 'Тема',
    'profile.stats.role': 'Роль',
    'profile.identity': 'Личность',
    'profile.identitySub': 'Аватар, отображаемое имя и статус аккаунта.',
    'profile.telegram': 'Telegram-аккаунт',
    'profile.telegramSub': 'Управляйте безопасной связкой сайт↔бот только здесь.',
    'profile.telegramUnlinked': 'Telegram пока не подключён.',
    'profile.telegramLinked': 'Telegram подключён и используется для синхронизации владения.',
    'profile.generateCode': 'Сгенерировать безопасный код',
    'profile.generateCopy': 'Создать и скопировать /link код',
    'profile.sendCode': 'Отправьте это боту в Telegram:',
    'profile.copyCommand': 'Скопировать команду',
    'profile.copied': 'Скопировано',
    'profile.copyFailed': 'Не удалось скопировать команду.',
    'profile.linkDetected': 'Telegram успешно подключён. Профиль обновлён.',
    'profile.waitingForLink': 'Ожидание привязки в Telegram…',
    'profile.unlink': 'Отвязать Telegram',
    'profile.linked': 'Подключено',
    'profile.unlinked': 'Не подключено',
    'profile.noUsername': 'Имя пользователя Telegram не задано',
    'profile.unknown': 'Неизвестный пользователь',
    'profile.contactPrefs': 'Контактные предпочтения',
    'profile.contactPrefsSub': 'Эти значения переиспользуются при создании объявлений на сайте и в боте.',
    'profile.displayName': 'Как к вам обращаться?',
    'profile.contactMethod': 'Предпочитаемый способ связи',
    'profile.contactDetails': 'Предпочитаемые контакты',
    'profile.contactPlaceholder': 'например @username, +7..., email или свой текст',
    'profile.pickupLocation': 'Обычное место/адрес выдачи',
    'profile.pickupPlaceholder': 'например Вестибюль общежития, станция Центр и т.п.',
    'profile.save': 'Сохранить профиль',
    'profile.saved': 'Профиль сохранён.',
    'profile.loadFailed': 'Не удалось загрузить профиль.',
    'profile.saveFailed': 'Не удалось сохранить профиль.',
    'profile.linkToEditTitle': 'Подключите Telegram для управления профилем',
    'profile.linkToEditSub': 'После подключения вы сможете сохранить контактные настройки для создания объявлений.',
  },
}

type SettingsContextValue = {
  theme: ThemeMode
  language: Language
  resolvedTheme: 'light' | 'dark'
  setTheme: (value: ThemeMode) => void
  setLanguage: (value: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const SettingsContext = createContext<SettingsContextValue | undefined>(undefined)

const interpolate = (template: string, params?: Record<string, string | number>) => {
  if (!params) return template
  return Object.entries(params).reduce((acc, [key, value]) => acc.split(`{{${key}}}`).join(String(value)), template)
}

const systemTheme = () => (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')

export const SettingsProvider = ({ children }: { children: ReactNode }) => {
  const [theme, setTheme] = useState<ThemeMode>(() => (localStorage.getItem(STORAGE_THEME) as ThemeMode) || 'system')
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem(STORAGE_LANGUAGE) as Language) || 'en')
  const [resolvedTheme, setResolvedTheme] = useState<'light' | 'dark'>(() => (typeof window === 'undefined' ? 'light' : systemTheme()))

  useEffect(() => {
    localStorage.setItem(STORAGE_THEME, theme)
  }, [theme])

  useEffect(() => {
    localStorage.setItem(STORAGE_LANGUAGE, language)
  }, [language])

  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)')
    const apply = () => {
      const next = theme === 'system' ? systemTheme() : theme
      setResolvedTheme(next)
      document.documentElement.setAttribute('data-theme', next)
    }

    apply()
    media.addEventListener('change', apply)
    return () => media.removeEventListener('change', apply)
  }, [theme])

  const value = useMemo<SettingsContextValue>(() => ({
    theme,
    language,
    resolvedTheme,
    setTheme,
    setLanguage,
    t: (key, params) => {
      const template = translations[language][key] ?? translations.en[key] ?? key
      return interpolate(template, params)
    },
  }), [theme, language, resolvedTheme])

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>
}

export const useSettings = () => {
  const value = useContext(SettingsContext)
  if (!value) {
    throw new Error('useSettings must be used within SettingsProvider')
  }
  return value
}
